{% set version = "0.4.0" %}
{% set python_min = "3.11.0" %}

package:
  name: jax-rrtmgp
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/j/jax-rrtmgp/jax_rrtmgp-{{ version }}.tar.gz
  sha256: 88529dce232c2eccf34867f5db164668985d33155e9368603ac9726e5e0691e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - dataclasses-json
    - jax
    - netcdf4
    - numpy

test:
  imports:
    - rrtmgp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/climate-analytics-lab/jax-rrtmgp
  dev_url: https://github.com/climate-analytics-lab/jax-rrtmgp
  summary: JAX-based implementation of RRTMGP radiative transfer for atmospheric modeling.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mahf708
